version: "3.9"

services:
  centrifugo:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo
    command: centrifugo -c /centrifugo/config.json
    ports:
      - "8000:8000"
      - "10000:10000"
    volumes:
      - ./deploy/centrifugo/config.local.json:/centrifugo/config.json:ro
    env_file:
      - .env
    restart: unless-stopped
