apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
  namespace: techinsight-notifications
type: Opaque
stringData:
  DATABASE_MONGODB_URI: "mongodb://mongo:27017"
  CACHE_REDIS_ADDR: "redis:6379"
  CACHE_REDIS_PASSWORD: ""
  KAFKA_BROKERS: "kafka:9092"
  CENTRIFUGO_API_URL: "http://centrifugo:8000/api"
  CENTRIFUGO_API_KEY: "CHANGE_ME"
  CENTRIFUGO_HMAC_SECRET: "CHANGE_ME"
